spring.application.name=rag-gemini

# Gemini API
gemini.api.key=${GEMINI_API_KEY}

# Supabase DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.apache.pdfbox=ERROR
logging.level.org.apache.fontbox=ERROR

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.hikari.data-source-properties.prepareThreshold=0